[package]
name = "test-runner"
version = "0.1.0"
edition = "2021"

[features]
console = []
gdb = []
socket = []

[dependencies]
ctru-rs = { git = "https://github.com/sardap/ctru-rs" }
ctru-sys = { git = "https://github.com/sardap/ctru-rs" }
libc = { workspace = true }
